apiVersion: v1
kind: Secret
metadata:
  name: coinapi
  namespace: adapters
type: Opaque
stringData:
  API_KEY: __API_KEY__
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coinapi-ingress
  namespace: adapters
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /coinapi-adapter(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: coinapi
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coinapi
  namespace: adapters
  labels:
    app: coinapi
spec:
  ports:
   - port: 8080
     targetPort: 8080
  selector:
   app: coinapi
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinapi
  namespace: adapters
  labels:
    app: coinapi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: coinapi
  template:
    metadata:
      labels:
        app: coinapi
    spec:
      containers:
        - name: coinapi
          image: coinapi-adapter:0.0.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          resources: {}
          envFrom:
            - secretRef:
                name: coinapi