apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coingecko-ingress
  namespace: adapters
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /coingecko-adapter(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: coingecko
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: coingecko
  namespace: adapters
  labels:
    app: coingecko
spec:
  ports:
   - port: 8080
     targetPort: 8080
  selector:
   app: coingecko
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coingecko
  namespace: adapters
  labels:
    app: coingecko
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: coingecko
  template:
    metadata:
      labels:
        app: coingecko
    spec:
      containers:
        - name: coingecko
          image: coingecko-adapter:0.0.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          resources: {}