apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: chainlink
---
apiVersion: v1
kind: Namespace
metadata:
  name: chainlink-rinkeby
---
apiVersion: v1
kind: Namespace
metadata:
  name: adapters
